Feature/restructure
i-dot-ai/automatilib pull request #3
Opened 2023-10-30 07:24 UTC by gecBurton

2023-10-30 07:25 UTC, gecBurton commented on README.rst
> +    - "cola.apps.ColaAuthConfig"
maybe should be    `"automatilib.apps.ColaAuthConfig"`

2023-10-30 07:26 UTC, gecBurton commented on cola/backend.py
> +    # def get_user(self, user_id):
i dont think we need this, at least it isnt showing up in the test coverage?

2023-10-30 07:27 UTC, gecBurton commented on cola/views.py
> -def get_cola_cognito_user_pool_jwk() -> Optional[tuple[dict, str]]:
i found a less aggressive way to mock this

2023-10-30 07:27 UTC, gecBurton commented on cola/views.py
> +class ColaLogin(View):
am open to what this should be called, but i think  we only need to say who we are once and not in ever class?

2023-10-30 07:28 UTC, gecBurton commented on cola/views.py
> -            return redirect(reverse(redirect_url or "index"))
there is already a default fall back for this not being set

2023-10-30 07:29 UTC, gecBurton commented on cola/views.py
> +        cola_cognito_user_pool_jwk = response.json()
I returned this to how you had it originally @252afh, which i think is better, after i found a better way to mock it

2023-10-30 07:30 UTC, gecBurton commented on cola/views.py
> +        token = ".".join(token.split(".")[:3])
```suggestion
```
i think we can come up with a regex expression that makes this step redundant

2023-10-30 07:30 UTC, gecBurton commented on cola/views.py
> +            LOGGER.error(f"cookie error: {error}")
i was getting str conversion errors with out this

2023-10-30 07:30 UTC, gecBurton commented on core/apps.py
> +class IdotAIConfig(AppConfig):
```suggestion
class CoreConfig(AppConfig):
```

2023-10-30 07:31 UTC, gecBurton commented on core/apps.py
> +    verbose_name = "i.AI's COLA Authentication"
```suggestion
    verbose_name = "i.AI's core models and utities"
```

2023-11-01 09:01 UTC, 252afh requested changes

2023-11-01 09:01 UTC, 252afh commented on automatilib/cola/backend.py
> +    # def get_user(self, user_id):
This is a required function for creating a new backend, even if it is never shown as being used

https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#:~:text=An%20authentication%20backend%20is%20a,optional%20permission%20related%20authorization%20methods.

2023-11-01 09:01 UTC, 252afh commented on automatilib/cola/models.py
Not needed

2023-11-01 09:01 UTC, 252afh commented on automatilib/cola/settings.py
Can move these here

```
INSTALLED_APPS = [
    "automatilib.cola",
]

AUTHENTICATION_BACKENDS = [
    "automatlib.cola.backend.AuthenticationBackend",
]
```

2023-11-01 09:01 UTC, 252afh commented on automatilib/cola/views.py
> +    def handle_user_jwt_details(self, user, token_payload: dict) -> None:
Why did we take away the `user` type, every user should inherit from djangos base user, or we can use django's method to get the instance of the user model in use

2023-11-01 09:01 UTC, 252afh commented on automatilib/cola/views.py
>          redirect_url = settings.LOGIN_REDIRECT_URL
Are we assuming this has to be set and index might not be in place?

2023-11-01 09:01 UTC, 252afh commented on automatilib/cola/views.py
> +            LOGGER.error("failed to get expected response from COLA")
Pedantic but capitalise the `f`

2023-11-01 09:01 UTC, 252afh commented on automatilib/cola/views.py
> +COLA_URL = f"{COLA_ISSUER}/.well-known/jwks.json"
This should be called `COLA_JWK_URL` instead, `COLA_URL` to me would refer to their login catch url

2023-11-01 09:01 UTC, 252afh commented on automatilib/cola/views.py
> +            LOGGER.info(f"Attempting to log user {user.pk} in")
Missing authenticating the user here

2023-11-01 09:01 UTC, 252afh commented on automatilib/cola/urls.py
> +    path("login/", views.ColaLogin.as_view(), name="login"),
This should be `post-login`, the `login` url is reserved for going out to COLA

2023-11-01 09:01 UTC, 252afh commented on automatilib/core/apps.py
> +    verbose_name = "i.AI's COLA Authentication"
verbose name is wrong

2023-11-01 09:01 UTC, 252afh commented on automatilib/core/migrations/__init__.py
Don't need an init in migrations

2023-11-01 09:01 UTC, 252afh commented on automatilib/core/models.py
> +    class Meta:
If this is abstract then we can get rid of the migrations

2023-11-01 09:01 UTC, 252afh commented on automatilib/core/settings.py
>  AUTH_USER_MODEL = "automatilib.core.User"
Can probably remove this if the user model is abstract

2023-11-01 09:01 UTC, 252afh commented on example_project/apps.py
> +    verbose_name = "i.AI's COLA Authentication"
verbose name is wrong

2023-11-01 09:01 UTC, 252afh commented on example_project/models.py
> +class MyUser(IDotAiUser, UUIDPrimaryKeyBase):
Do we need a migration for this user?

2023-11-01 09:19 UTC, gecBurton commented on automatilib/cola/views.py
> +    def handle_user_jwt_details(self, user, token_payload: dict) -> None:
ah good question, i forget exactly what the issue is, I think django was complaining that we were using a model that was registered to any app, probably we can use an abstract Model though.. i'll give it a go

2023-11-01 09:20 UTC, gecBurton commented on automatilib/cola/views.py
>          redirect_url = settings.LOGIN_REDIRECT_URL
there is a default provided my the ModelBackend, i think it is `accounts/login`

2023-11-01 09:21 UTC, gecBurton commented on automatilib/cola/views.py
> +    def handle_user_jwt_details(self, user, token_payload: dict) -> None:
https://github.com/i-dot-ai/automatilib/pull/3#discussion_r1378537959 I think this is related

2023-11-01 09:21 UTC, gecBurton commented on example_project/models.py
> +class MyUser(IDotAiUser, UUIDPrimaryKeyBase):
apparently not as the tests pass without it, but probably worth adding one

2023-11-01 09:23 UTC, gecBurton commented on automatilib/cola/views.py
> +            LOGGER.error("failed to get expected response from COLA")
```suggestion
            LOGGER.error("Failed to get expected response from COLA")
```

2023-11-01 09:24 UTC, gecBurton commented on automatilib/cola/views.py
> +            LOGGER.info(f"Attempting to log user {user.pk} in")
isnt this done on line 137?

2023-11-01 09:24 UTC, gecBurton commented on automatilib/core/apps.py
> +    verbose_name = "i.AI's COLA Authentication"
```suggestion
    verbose_name = "i.AI's core models"
```

2023-11-01 09:25 UTC, gecBurton commented on example_project/apps.py
> +    verbose_name = "i.AI's COLA Authentication"
```suggestion
    verbose_name = "example application using COLA Authentication"
```

2023-11-01 10:24 UTC, gecBurton commented on automatilib/cola/views.py
> +COLA_URL = f"{COLA_ISSUER}/.well-known/jwks.json"
[597dbe7](https://github.com/i-dot-ai/automatilib/pull/3/commits/597dbe74e264d93fc24d447d5537c78d135cb8b6)

2023-11-01 10:24 UTC, gecBurton commented on automatilib/cola/urls.py
> +    path("login/", views.ColaLogin.as_view(), name="login"),
[6e0d166](https://github.com/i-dot-ai/automatilib/pull/3/commits/6e0d16647f6a42f3c13c0af558ea7bd0aa71f217)

2023-11-01 10:31 UTC, gecBurton commented on automatilib/cola/models.py
[13d7c5f](https://github.com/i-dot-ai/automatilib/pull/3/commits/13d7c5f78e671231a8ea959d4b8e02bb249e0a86)

2023-11-01 10:31 UTC, gecBurton commented on automatilib/cola/backend.py
> +    # def get_user(self, user_id):
[d58b30b](https://github.com/i-dot-ai/automatilib/pull/3/commits/d58b30bceeff850176332f1784af200f2df22346)

2023-11-01 10:46 UTC, gecBurton commented on automatilib/cola/settings.py
see [8793fb9](https://github.com/i-dot-ai/automatilib/pull/3/commits/8793fb9530152954a01da5642568abfeaec50fc0) 

I could remove stuff from the example_project/settings.py but adding it to cola/settings.py didnt make any difference

2023-11-01 11:24 UTC, gecBurton commented on example_project/models.py
> +class MyUser(IDotAiUser, UUIDPrimaryKeyBase):
added here [29bacb0](https://github.com/i-dot-ai/automatilib/pull/3/commits/29bacb061e44879b687bb97cc66207c85dbf51cc)

2023-11-01 11:56 UTC, 252afh commented on automatilib/cola/views.py
> +            LOGGER.info(f"Attempting to log user {user.pk} in")
So it is

2023-11-01 12:00 UTC, 252afh commented on automatilib/cola/settings.py
Including it using string quotes makes this part redundant. We can import it into our django-apps settings file and do 

```
import settings from automatilib.core as AUTOMATILIB_SETTINGS 
import settings from automatilib.cola as COLA_SETTINGS 

INSTALLED_APPS = [
"other_stuff",
*COLA_SETTINGS.COLA_INSTALLED_APPS,
*AUTOMATILIB_SETTINGS.AUTOMATILIB_INSTALLED_APPS,
]
```

Or scrap the whole thing and let the user import using strings

2023-11-01 12:03 UTC, 252afh commented on automatilib/cola/views.py
>          redirect_url = settings.LOGIN_REDIRECT_URL
That relies on the user having all_auth in use. Plus this is the post-login url, so it's a just-in-case clause if for some weird reason they haven't set the url

2023-11-01 12:05 UTC, 252afh commented on automatilib/core/settings.py
>  AUTH_USER_MODEL = "automatilib.core.User"
By `this` I mean `AUTH_USER_MODEL = "automatilib.core.User"` btw, highlighting isn't obvious in git for me

2023-11-01 12:21 UTC, gecBurton commented on automatilib/core/settings.py
>  AUTH_USER_MODEL = "automatilib.core.User"
ah, i removed `AUTH_USER_MODEL = "automatilib.core.User` too

2023-11-01 12:26 UTC, gecBurton commented on automatilib/cola/settings.py
> Or scrap the whole thing and let the user import using strings

tbh i think i prefer this as its very clear?

2023-11-01 12:31 UTC, gecBurton commented on automatilib/cola/settings.py
[ac32f6d](https://github.com/i-dot-ai/automatilib/pull/3/commits/ac32f6d629030e3dc909a7a60e864bf30722ce80)

> Or scrap the whole thing and let the user import using strings

i went for this option as it was clearer, happy to change though

2023-11-01 12:34 UTC, gecBurton commented on automatilib/cola/views.py
>          redirect_url = settings.LOGIN_REDIRECT_URL
[de37f](https://github.com/i-dot-ai/automatilib/pull/3/commits/14de37fb4568088e40f778d5fe033389e2b167b4)

2023-11-02 09:03 UTC, 252afh commented on automatilib/cola/settings.py
The core settings file can be deleted as well in that case :)

2023-11-02 09:37 UTC, 252afh approved these changes

2023-11-02 09:39 UTC, merged